#!/bin/bash

if [ -z $1 ]; then
  echo 'Need a directory to search'
  exit 1
fi

if [ ! -d $1 ]; then
  echo 'Need a directory to search for git repos.'
  exit 1
fi

cd $1

SUBDIRS=`ls -d */`

absolut=`pwd`

for DIR in $SUBDIRS
do
  path="$absolut/$DIR"
  cd $path
  git rev-parse --is-inside-work-tree &>/dev/null
  if [ $? -eq 0 ]; then
    git pull
  fi
done
