#!/bin/bash
function git_fetcher()
{
  cd $1
  git rev-parse --is-inside-work-tree &>/dev/null
  if [ $? -eq 0 ]; then
    git pull
  fi
}

if [ $1 ]; then
  if [ ! -d $1 ]; then
    echo 'Need a directory to search for git repos.'
    exit 1
  fi
fi

if [ $1 ]; then
  cd $1
fi

SUBDIRS=`ls -d */`
absolut=`pwd`

for DIR in $SUBDIRS
do
  path="$absolut/$DIR"
  echo "Fetching $DIR"
  git_fetcher $path &>/dev/null &
done

# search in all subfolders for git-repos

# determine git repo for information
